//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Details
    {
        public string Book_id { get; set; }
        public string Book_name { get; set; }
        public string Book_author { get; set; }
    }
}
