//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrower_Table
    {
        public int Borrower_Id { get; set; }
        public Nullable<int> Book_Id { get; set; }
        public Nullable<System.DateTime> Borrow_Date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
    }
}
