//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indhu_Book
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string BAuthor { get; set; }
        public string BEdition { get; set; }
        public string BPublish { get; set; }
        public Nullable<int> BCopies { get; set; }
    }
}
