//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Book_Details
    {
        public int Book_ID { get; set; }
        public string Book_Name { get; set; }
        public string Author { get; set; }
        public string Edition { get; set; }
        public string Publish { get; set; }
        public Nullable<int> Copies { get; set; }
    }
}
